# FixMyPDF Features & Resources Site Configuration
title: "FixMyPDF Tools & Resources"
description: "Comprehensive guides, tutorials, and resources for PDF manipulation using FixMyPDF's 70+ browser-based tools"
url: "https://yourusername.github.io"
baseurl: "/fixmypdf-features"

# Author information
author:
  name: "FixMyPDF Team"
  url: "https://fixmypdf.in"

# SEO and social
lang: en_US
timezone: UTC
google_analytics: G-E4EEPVZ1MG
social:
  links:
    - "https://fixmypdf.in"

# Jekyll configuration
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

# Plugin configuration
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from

# Collections for organized content
collections:
  tools:
    output: true
    permalink: /tools/:name/
  guides:
    output: true
    permalink: /guides/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "FixMyPDF Team"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"

# Build settings
safe: true
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# RSS feed settings
feed:
  posts_limit: 20
  excerpt_only: true

# Site navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Tools Guide"
    url: "/tools/"
  - title: "Blog"
    url: "/blog/"
  - title: "Resources"
    url: "/guides/"
  - title: "Main Site"
    url: "https://fixmypdf.in"
    external: true